const HARLEY_OPTION = [
{value:'1200 나잇스터'},
{value:'883'},
{value:'883 R'},
{value:'883 로우'},
{value:'883 슈퍼로우'},
{value:'883 커스텀'},
{value:'883 허그'},
{value:'CVO 로드 글라이드'},
{value:'CVO 로드 글라이드 울트라'},
{value:'CVO 로드 글라이드 커스텀'},
{value:'CVO 로드킹'},
{value:'CVO 리미티드'},
{value:'CVO 브래이크아웃'},
{value:'CVO 소프테일 컨버터블'},
{value:'CVO 스트리트 글라이드'},
{value:'CVO 와이드 글라이드'},
{value:'CVO 울트라 클래식'},
{value:'CVO 울트라 클래식 일랙트라 글라이드'},
{value:'CVO 팻 밥'},
{value:'FCL'},
{value:'FL'},
{value:'FLH'},
{value:'FX'},
{value:'FXDR 114'},
{value:'FXDRS'},
{value:'M 50'},
{value:'나이트로드'},
{value:'나이트로드 스페셜'},
{value:'나이트트레인'},
{value:'노스텔지아'},
{value:'다이나 CVO'},
{value:'다이나 로우라이더'},
{value:'다이나 로우라이더 S'},
{value:'다이나 스위치백'},
{value:'다이나 컨버터블'},
{value:'다이나로우글라이드'},
{value:'다이나슈퍼글라이드'},
{value:'다이나슈퍼글라이드 T스포츠'},
{value:'다이나슈퍼글라이드스포츠'},
{value:'다이나슈퍼글라이드커스텀'},
{value:'다이나스트릿밥'},
{value:'다이나와이드글라이드'},
{value:'다이나팻밥'},
{value:'락커'},
{value:'락커C'},
{value:'로드 글라이드'},
{value:'로드 글라이드 리미티드'},
{value:'로드 글라이드 스페셜'},
{value:'로드 글라이드 울트라'},
{value:'로드 글라이드 커스텀'},
{value:'로드스터 1200'},
{value:'로드킹'},
{value:'로드킹 스페셜'},
{value:'로드킹커스텀'},
{value:'로드킹클래식'},
{value:'배드보이'},
{value:'브래이크아웃'},
{value:'브래이크아웃 114'},
{value:'브이로드'},
{value:'브이로드 A'},
{value:'브이로드 머슬'},
{value:'블랙라인'},
{value:'세븐티 투'},
{value:'소프테일'},
{value:'소프테일 로우라이더'},
{value:'소프테일 슬림'},
{value:'소프테일 슬림 S'},
{value:'소프테일 팻밥'},
{value:'소프테일듀스'},
{value:'소프테일디럭스'},
{value:'소프테일스프링거'},
{value:'소프테일커스텀'},
{value:'슈퍼글라이드 1340'},
{value:'슈퍼로우 1200 T'},
{value:'스트리트 로드 750'},
{value:'스트리트 밥'},
{value:'스트리트 밥 114'},
{value:'스트리트글라이드'},
{value:'스트리트글라이드 스페셜'},
{value:'스트리트로드'},
{value:'스트릿 500'},
{value:'스트릿 750'},
{value:'스트릿 스토커'},
{value:'스포스터 1200 로드스터'},
{value:'스포스터 1200 로우'},
{value:'스포스터 1200 스포츠'},
{value:'스포스터 1200 커스텀'},
{value:'스포스터 1200 하이'},
{value:'스포스터 S'},
{value:'스포스터 XL 50'},
{value:'스포스터 XR 1200'},
{value:'스포스터 XR 1200 X'},
{value:'스포츠 글라이드'},
{value:'스프링거클래식'},
{value:'아이언 1200'},
{value:'아이언 883'},
{value:'와이드 글라이드'},
{value:'울트라 리미티드 로우'},
{value:'울트라 클래식'},
{value:'울트라 클래식 일렉트라 글라이드'},
{value:'일랙트라 글라이드 울트라 클래식 로우'},
{value:'일렉트라 글라이드'},
{value:'일렉트라 글라이드 리바이벌'},
{value:'일렉트라 글라이드 울트라 리미티드'},
{value:'일렉트라 글라이드 클래식'},
{value:'커스텀쵸퍼'},
{value:'크로스본'},
{value:'트라이 글라이드 울트라 클래식'},
{value:'팬 아메리카 1250'},
{value:'팬 아메리카 1250 스페셜'},
{value:'팻밥 103'},
{value:'팻밥 107'},
{value:'팻밥 114'},
{value:'팻보이'},
{value:'팻보이 107'},
{value:'팻보이 114'},
{value:'팻보이 S'},
{value:'팻보이 스페셜'},
{value:'포티에잇 48'},
{value:'포티에잇 스페셜'},
{value:'헤리티지소프테일'},
{value:'헤리티지소프테일클래식'},
{value:'헤리티지스피링거'}]

export default HARLEY_OPTION