const MOTOGUZZI_OPTION =
[{value:'1200 스포츠 4V'},
{value:'AUDACE'},
{value:'V 11'},
{value:'V 11 LE MANS'},
{value:'V 11 스포츠'},
{value:'V 35'},
{value:'V7'},
{value:'V7 II 레이서'},
{value:'V7 III ROUGH'},
{value:'V7 III 밀라노'},
{value:'V7 III 카본'},
{value:'V7 Ⅱ'},
{value:'V7 Ⅱ 스톤'},
{value:'V7 Ⅱ 스페셜 ABS'},
{value:'V7 Ⅱ스톤 ABS'},
{value:'V7 Ⅲ ANNIVERSARIO'},
{value:'V7 Ⅲ 레이서'},
{value:'V7 Ⅲ 스톤'},
{value:'V7 Ⅲ 스페셜'},
{value:'V7 까페 클래식'},
{value:'V7 레이서'},
{value:'V7 스톤'},
{value:'V7 스페셜'},
{value:'V7 클래식'},
{value:'V9 롬머'},
{value:'V9 바버'},
{value:'그리소 1100'},
{value:'그리소 1200 8V'},
{value:'그리소 850'},
{value:'노지 1200'},
{value:'노지 850'},
{value:'브레바 1100'},
{value:'브레바 1200'},
{value:'브레바 750'},
{value:'브레바 850'},
{value:'스텔비오 1200 4V'},
{value:'엘도라도'},
{value:'자칼'},
{value:'캘리포니아 EV'},
{value:'캘리포니아 빈티지'},
{value:'캘리포니아 클래식'},]

export default MOTOGUZZI_OPTION