const TRIUMPH_OPTION = [
{value:'TT 600'},
{value:'데이토나 675'},
{value:'데이토나 955 I'},
{value:'레젼드 TT'},
{value:'로켓Ⅲ GT'},
{value:'로켓Ⅲ R'},
{value:'본네빌'},
{value:'본네빌 T100'},
{value:'본네빌 T100 폴스미스'},
{value:'본네빌 T120'},
{value:'본네빌 T120 블랙'},
{value:'본네빌 T214'},
{value:'본네빌 바버'},
{value:'본네빌 바버 블랙'},
{value:'스크램블러'},
{value:'스크램블러 1200 XC'},
{value:'스크램블러 1200 XE'},
{value:'스트릿 스크램블러'},
{value:'스트릿 트리플 RS'},
{value:'스트릿 트윈'},
{value:'스프린트 RS'},
{value:'스프린트 ST'},
{value:'스피드 마스터'},
{value:'스피드 트리플'},
{value:'스피드 트리플 1050 R'},
{value:'스피드 트윈'},
{value:'스피드 포'},
{value:'썬더버드'},
{value:'썬더버드 스포츠'},
{value:'썬버드 스포츠'},
{value:'아메리카'},
{value:'어드벤쳐'},
{value:'타이거 1050'},
{value:'타이거 110'},
{value:'타이거 1200 익스플로어 XCA'},
{value:'타이거 800'},
{value:'타이거 900'},
{value:'타이거 900 GT'},
{value:'타이거 900 랠리'},
{value:'타이거 900 랠리 프로'},
{value:'트라이던트 660'},
{value:'트럭스턴'},
{value:'트럭스턴 R'},
{value:'트럭스턴 RS'},
{value:'트로피 1200'},
{value:'트로피 900'},]

export default TRIUMPH_OPTION